services:
  node1:
    build: .
    environment:
      - NODE_ID=node1
      - CLUSTER_NODES=node1,node2,node3,node4,node5
      - PORT=3000
    ports:
      - "3001:3000"
    volumes:
      - node1_data:/app/data
    networks:
      raft-network:
        aliases:
          - node1
      client-network: {}

  node2:
    build: .
    environment:
      - NODE_ID=node2
      - CLUSTER_NODES=node1,node2,node3,node4,node5
      - PORT=3000
    ports:
      - "3002:3000"
    volumes:
      - node2_data:/app/data
    networks:
      raft-network:
        aliases:
          - node2
      client-network: {}

  node3:
    build: .
    environment:
      - NODE_ID=node3
      - CLUSTER_NODES=node1,node2,node3,node4,node5
      - PORT=3000
    ports:
      - "3003:3000"
    volumes:
      - node3_data:/app/data
    networks:
      raft-network:
        aliases:
          - node3
      client-network: {}

  node4:
    build: .
    environment:
      - NODE_ID=node4
      - CLUSTER_NODES=node1,node2,node3,node4,node5
      - PORT=3000
    ports:
      - "3004:3000"
    volumes:
      - node4_data:/app/data
    networks:
      raft-network:
        aliases:
          - node4
      client-network: {}

  node5:
    build: .
    environment:
      - NODE_ID=node5
      - CLUSTER_NODES=node1,node2,node3,node4,node5
      - PORT=3000
    ports:
      - "3005:3000"
    volumes:
      - node5_data:/app/data
    networks:
      raft-network:
        aliases:
          - node5
      client-network: {}

  client1:
    build: .
    command: npm run client
    tty: true
    stdin_open: true
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      client-network:
        aliases:
          - client1

  client2:
    build: .
    command: npm run client
    tty: true
    stdin_open: true
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      client-network:
        aliases:
          - client2

volumes:
  node1_data:
  node2_data:
  node3_data:
  node4_data:
  node5_data:

networks:
  raft-network:
    driver: bridge
  client-network:
    driver: bridge
